### ISSUE TITLE
Same thing, only as a simple bash scriipt

### ISSUE THREAD

**Issue by hopeseekr** [aeon-php/automation#24]
Hi,

I'm banned from /r/PHP because they don't like me helping others with my own code snippets, but...

I made this same thing months ago in pure Bash. Works with any language, even if PHP isn't available.

https://github.com/hopeseekr/BashScripts/blob/trunk/changelog-maker-lite

Cheers!

**Comment by norberttech** [comment]
Hey @hopeseekr 
My goal was to make it possible to generate output in https://keepachangelog.com/en/1.0.0/ format which seems to be out of the scope of your script. Your version is definitely lighter and faster, but it looks that simplicity comes with a natural cost of limited possibilities and flexibility, but that's fine. In most cases, easier is better, at least at the beginning.  
I truly admire simplicity and purity and if my use case would not be a bit over possibilities of your solution, I would happily drop what I have built here! 

I'm now going to close this is issue if you don't mind. Good luck with your projects! 

Either way, thanks for sharing! 🙌
