### ISSUE TITLE
GitHub Enterprise support

### ISSUE THREAD

**Issue by ameir** [aeon-php/automation#27]
I was really looking forward to using this project, but it appears that it only works for public GitHub repositories. I was looking to use it on GHE (self-hosted), but I don't know if that's possible. Is there a way to get this to work?

**Comment by norberttech** [comment]
It seems that the GitHub library Automation is using supports enterprise instances.
https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Client.php

I’ll look into this and think how to pass the URL, most likely through eng var/option, just like GitHub token

**Comment by norberttech** [comment]
Hey @ameir I think this https://github.com/aeon-php/automation/pull/28 should do the job, could you please test it and let me know if it works? I don't have access to any GitHub enterprise instance currently. 
I'm closing this issue, for now, feel free to reopen it if it won't work.

**Comment by ameir** [comment]
Thanks for the prompt resolution! I was thankfully able to get this to work as expected. 

When you have cycles, would you be able to push a new Docker image? I did a `composer update` within the latest image, which works, but of course that's not ideal. Thanks again!

**Comment by norberttech** [comment]
You are right, docker is the right way to go! I forgot to update image, sorry, it's fixed now.

If you have any feedback about the app, if you are missing anything please let me know ✌️
