### ISSUE TITLE
Tag filtering

### ISSUE THREAD

**Issue by ameir** [aeon-php/automation#29]
Hello,

I have a number of tags (~100), and most have a `-beta` or `-pre` or similar type of suffix for tags between full releases. I am looking to generate changelogs only on merges to the main branch, and would want to show changes between, e.g. 0.6.2 and 0.6.3, but don't want to show 0.6.3-beta or whatever other intermediate tags there are. Is there currently a way to do this?

To be clear, I want to generate a changelog for the entire repo, and not just from last release to this one. Thanks for the great project!

**Comment by norberttech** [comment]
Good one! I have one project of my own that has a similar problem. Let me think more about it, probably later next week.
Currently I’m working on changelog manipulation, so after successful release/merge, automation will open a pull request with an updated changelog file.

**Comment by norberttech** [comment]
Hey, I think I found an elegant solution for your problem, I think that `--only-stable` option added to `changelog:generate:all` should do the job, it will filter out tags with stability different than semver `stable` so all commits under 1.0.0-alpha and 1.0.0-beta would go simply under 1.0.0. 
Makes sense?

**Comment by norberttech** [comment]
option `--tag-only-stable` is now available, let me know if that won't solve your issue
